apiVersion: v1
kind: Service
metadata:
  name: drivestream-service
spec:
  type: NodePort
  selector:
    app: drivestream-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007